### ISSUE TITLE
Go through features from #neu-todo-before-2.0

### ISSUE THREAD

**Issue by DoKM** [DoKM/NotEnoughUpdates#1]
//List is copied from #neu-todo-before-2.0 and might include things that will not be changed/added/fixed or things that are already fixed but not listed
- [ ] disable hyperion particles doesnt work some of the time prob bc when they changed the range they changed the particles
- [ ] this pet crash https://canary.discord.com/channels/516977525906341928/714332750156660756/833161782851141702
- [ ] the tails thing doesnt work https://canary.discord.com/channels/516977525906341928/738199566977073262/828946911797051402
- [ ] sbmenu is fucked prob same thing as tails
- [ ] ench thing bugged cos remove block clicks https://canary.discord.com/channels/516977525906341928/738199566977073262/826789199817736192
- [ ] todo timers https://canary.discord.com/channels/516977525906341928/738199566977073262/821981685818196009
- [ ] fetchur is wrong https://canary.discord.com/channels/516977525906341928/738199566977073262/816542157162676234
- [ ] wood in pv from 6 months ago https://canary.discord.com/channels/516977525906341928/738199566977073262/764906334130274335 
- [ ] dark colors with packhq https://canary.discord.com/channels/516977525906341928/738199566977073262/781647613673078814
- [ ] boots dont show 2nd page of wardrobe https://canary.discord.com/channels/516977525906341928/738199566977073262/800654175901712384
- [ ] no toggle for farming crystal overlay
- [ ] drill parts in the forge show pickaxe cooldown https://canary.discord.com/channels/516977525906341928/738199566977073262/802695105437630514
- [ ] damage numbers with a weird symbol dont get commas https://canary.discord.com/channels/516977525906341928/738199566977073262/805021908290633730
- [ ] If you are holding bow map appears in boss (kinda useful tho) https://canary.discord.com/channels/516977525906341928/738199566977073262/809354643518914560
- [ ] Sba broke backpack code again 
- [ ] https://canary.discord.com/channels/516977525906341928/738199566977073262/812144091382415391 (idk if this is fixed)
- [ ] fix pet on the first page of pv https://canary.discord.com/channels/516977525906341928/738199566977073262/812913716592640040
- [ ] this says 0/2 https://canary.discord.com/channels/516977525906341928/738199566977073262/813834323941654578
- [ ] percent of 2 pets shows the percent of the pet in use https://canary.discord.com/channels/516977525906341928/738199566977073262/815836559177416767
- [ ] pet info persistence
- [ ] neu skulls toggle
- [ ] guiinventory cast crash
- [ ] add /neubuttons microtransaction feature ($0.50 per button)
- [ ] better presets in the button menu
- [ ] disable todo overlay by default
- [ ] also just fix todo overlay
- [ ] tab complete ah search
- [ ] improved ah price selection + prevent putting up undervalued items (im looking at u nullzee selling storm leggings for 2.8m)

- [ ] option to only show price information when a key is held
- [ ] oh god i can already feel myself wanting to add random shit that no one will care about
- [ ] automatically make users subscribe to my youtube channel so i can get red name
- [ ] (maybe) item customization gui (rename + change skull texture + change dye value) (idk might get people scammed but tbh if you trust someone because they ss you are a special kind of stupid)
- [ ] make bonemerang thingy not work on invisible entities
- [ ] pickaxe cooldown stuff
- [ ] titanium who is not accessible show alert : https://canary.discord.com/channels/516977525906341928/693600396492537896/820618152534343680
- [ ] titanium who is insta mined still alert : https://canary.discord.com/channels/516977525906341928/693600396492537896/818430373670420510
- [ ] titanium alert appear when the commission is DONE : https://canary.discord.com/channels/516977525906341928/693600396492537896/823521870443839498 
- [ ] titanium alert appear even if you are in a different location to the commission
- [ ] auto recomb don't appear in missing talismans, there may be others talismans missing : https://canary.discord.com/channels/516977525906341928/737414807250272258/821780470407626816
- [ ] Ghast star toggle

- [ ] drill parts in the forge show pickaxe cooldown https://canary.discord.com/channels/516977525906341928/738199566977073262/802695105437630514
- [ ] If you are holding bow map appears in boss (kinda useful tho) https://canary.discord.com/channels/516977525906341928/738199566977073262/809354643518914560
- [ ] Everything from here: https://canary.discord.com/channels/516977525906341928/833237325193936927/833301254460932116
- [ ] Order by Item Worth in the item list dosent work.
- [ ] Dwarf Turtle Shelmet does not show as a held item in the pet overlay
- [ ] Dungeon Items don't appear in the Item List Category's 
- [ ] Overlays (like Farming Overlay) overlap with vanilla things like tablist or chat
- [ ] Missing enchants does not work on Fishing Weapons (e.g Phantom Rod)
- [ ] Slot Binding Line looks weird when hovering over tooltips https://cdn.discordapp.com/attachments/659613194066722833/851863107197468703/unknown.png

- [ ] Boots dont show 2nd page of wardrobe https://canary.discord.com/channels/516977525906341928/738199566977073262/800654175901712384
- [ ] wood in pv from 6 months ago https://canary.discord.com/channels/516977525906341928/738199566977073262/764906334130274335
- [ ] Add Ironman Symbole to the player model on the first page
- [ ] Add T5 Zombie Slayer on the 3rd Page
- [ ] Add Enderman Slayer on the first and third Page
- [ ] Add Storage/personal vault 
- [ ] Add Mthril Minion/Collection
- [ ] Add Hardstone Minion/Collection
- [ ] Add Voidling Minion to PV
- [ ] Show Tier of a Minion
- [ ] Add Pet Candy to Pets
- [ ] Add Pet Skins to Pets
- [ ] Add Link to Skycrypt Button
- [ ] Add Missing Talismans 
- [ ] Add Profile created, guild and last online to the 3rd page (empty space)
- [ ] Add a Button that opens pv in the Player Profile (right click on a player)#
- [ ] Add Total Slayer XP to the 3rd Page
- [ ] Ability to disable scrolling to 10th slot https://canary.discord.com/channels/516977525906341928/693600396492537896/851817457043111976
- [ ] Ability to save & share presets in /neubuttons
- [ ] Add Help Button to /neuec (like in neucustomize)
- [ ] Ability to save & share presets in /neuec
- [ ] Auto complete enchants /neuec (small example https://cdn.discordapp.com/attachments/659613194066722833/851864695702683698/unknown.png professional paint skills)
- [ ] Add a Info in your Inventory when you enable the searchmode (onetime)
- [ ] Add /neuhelp for a command list
- [ ] Add Twitch link to /neulinks (so you get more money)
- [ ] Add Help Button to /neucosmetics so people know how they can get capes

**Comment by jani270** [comment]
Cleanup and Revamp #14, Issue can be closed
