### ISSUE TITLE
NEU Todo Before 2.0 v2 (Cleanup)

### ISSUE THREAD

**Issue by jani270** [DoKM/NotEnoughUpdates#14]
**PV Suggestion & Bugs:**
- [x] Add Master mode XP to cata calculator
- [x] Fix CataXP calculator for normal floors

**Other Suggestion & Bugs** 
- [ ] make bonemerang thingy not work on invisible entities (enderman in dungeons)
- [x] Add Help Button to /neuec (like in neucustomize)
- [ ] Add Preview of Armor etc in /neuec (with tier selection)
- [ ] Auto complete enchants /neuec: small example [here](https://cdn.discordapp.com/attachments/659613194066722833/851864695702683698/unknown.png) 
- [ ] drill parts in the forge show pickaxe cooldown more info [here](https://canary.discord.com/channels/516977525906341928/738199566977073262/802695105437630514))
- [ ] titanium who is insta mined still alert (more info [here]( https://canary.discord.com/channels/516977525906341928/693600396492537896/818430373670420510))
- [ ] titanium alert appear even if you are in a different location to the commission (idk if already fixed)
- [x] Treecap/jungle axe cooldown not working when cutting down trees in places with instant mine (private island/park)
  - Bug seems to be caused by the block not being added to the blocksClicked array
  - When clicking fast before chopping the tree it does activate
- [x]  Make scrolling in /neu work (or make it work with arrow keys)
- [ ] Take a look at neucalendar, it disappears sometimes. (restarting fixes the bug)
- [ ] Move the search thing the top left and make a field where you can type
- [ ] Slotbinding - Add something like [this](https://prnt.sc/1oqsyuo) for armor to hotbar (other way around the same but for armor slots)
- [ ] when having Titanium Miner x/15, the title with titanium nearby does not pop up
